import { USER_ROLES, APPLICATION_STATUS } from '../constants';

export const INITIAL_USERS = [
  {
    id: 'user_seeker_1',
    email: 'seeker@jobconnect.demo',
    password: 'password123',
    role: USER_ROLES.JOB_SEEKER,
    name: 'Aarav Sharma',
    phone: '+91 98765 43210',
    headline: 'Senior Full Stack React & Node Developer',
    location: 'Ahmedabad, Gujarat',
    bio: 'Passionate software engineer with 5+ years of experience crafting high-performance web applications with React, TypeScript, and Node.js.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    profileCompletion: 92,
    skills: ['React', 'JavaScript', 'TypeScript', 'Node.js', 'Redux', 'Tailwind CSS', 'PostgreSQL', 'Docker', 'AWS'],
    languages: [
      { name: 'English', proficiency: 'Fluent' },
      { name: 'Hindi', proficiency: 'Native' },
      { name: 'Gujarati', proficiency: 'Conversational' },
    ],
    experience: [
      {
        id: 'exp_1',
        title: 'Lead Frontend Engineer',
        company: 'InnovateX Labs',
        location: 'Ahmedabad, Gujarat',
        startDate: '2022-03',
        endDate: 'Present',
        current: true,
        description: 'Led a team of 6 engineers building scalable enterprise dashboards. Improved core web vitals by 45%.',
      },
      {
        id: 'exp_2',
        title: 'Software Developer',
        company: 'TechWave Solutions',
        location: 'Mumbai, Maharashtra',
        startDate: '2019-06',
        endDate: '2022-02',
        current: false,
        description: 'Developed responsive client portals, integrated RESTful APIs, and wrote automated unit tests with Jest.',
      },
    ],
    education: [
      {
        id: 'edu_1',
        degree: 'B.Tech in Computer Engineering',
        institution: 'Gujarat Technological University (GTU)',
        year: '2015 - 2019',
        score: '8.8 CGPA',
      },
    ],
    projects: [
      {
        id: 'proj_1',
        title: 'FinTrack - AI Expense Manager',
        link: 'https://github.com/example/fintrack',
        description: 'Personal finance web app with automated OCR receipt scanning and monthly budgeting analytics.',
      },
    ],
    resume: {
      fileName: 'Aarav_Sharma_FullStack_Resume.pdf',
      fileSize: '420 KB',
      uploadedAt: '2026-09-15T10:30:00.000Z',
      url: '#',
    },
    savedJobs: ['job_1', 'job_3', 'job_7'],
    createdAt: '2026-01-10T08:00:00.000Z',
    status: 'active',
  },
  {
    id: 'user_employer_1',
    email: 'employer@techcorp.demo',
    password: 'password123',
    role: USER_ROLES.EMPLOYER,
    name: 'Priya Patel',
    phone: '+91 91234 56789',
    headline: 'Talent Acquisition Director',
    companyId: 'comp_1',
    companyName: 'TechCorp Innovations',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-05T09:00:00.000Z',
    status: 'active',
  },
  {
    id: 'user_employer_2',
    email: 'hr@razorpay.demo',
    password: 'password123',
    role: USER_ROLES.EMPLOYER,
    name: 'Vikram Mehta',
    phone: '+91 99887 76655',
    headline: 'Senior Tech Recruiter',
    companyId: 'comp_7',
    companyName: 'Razorpay',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-12T11:00:00.000Z',
    status: 'active',
  },
  {
    id: 'user_employer_3',
    email: 'recruiting@zerodha.demo',
    password: 'password123',
    role: USER_ROLES.EMPLOYER,
    name: 'Sneha Reddy',
    phone: '+91 98111 22334',
    headline: 'Head of People & Culture',
    companyId: 'comp_9',
    companyName: 'Zerodha',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-02-01T10:00:00.000Z',
    status: 'active',
  },
  {
    id: 'user_admin_1',
    email: 'admin@jobconnect.demo',
    password: 'password123',
    role: USER_ROLES.ADMIN,
    name: 'Super Admin',
    phone: '+91 90000 00001',
    headline: 'JobConnect System Administrator',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    createdAt: '2025-12-01T00:00:00.000Z',
    status: 'active',
  },
  // Additional Seekers for recruiter candidate search
  {
    id: 'user_seeker_2',
    email: 'rohit.verma@example.com',
    role: USER_ROLES.JOB_SEEKER,
    name: 'Rohit Verma',
    headline: 'Backend Python & Django Specialist | AWS Certified',
    location: 'Bangalore, Karnataka',
    skills: ['Python', 'Django', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    experience: [{ title: 'Senior Backend Developer', company: 'CloudScale', current: true, startDate: '2021-01', endDate: 'Present' }],
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    profileCompletion: 88,
    status: 'active',
  },
  {
    id: 'user_seeker_3',
    email: 'ananya.joshi@example.com',
    role: USER_ROLES.JOB_SEEKER,
    name: 'Ananya Joshi',
    headline: 'Lead UI/UX & Product Designer',
    location: 'Mumbai, Maharashtra',
    skills: ['Figma', 'UI/UX Design', 'Design Systems', 'User Research', 'Prototyping', 'Tailwind CSS'],
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    profileCompletion: 95,
    status: 'active',
  },
  {
    id: 'user_seeker_4',
    email: 'karan.singh@example.com',
    role: USER_ROLES.JOB_SEEKER,
    name: 'Karan Singh',
    headline: 'DevOps & Cloud Architect (Kubernetes, Terraform, GCP)',
    location: 'Remote (India)',
    skills: ['Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'AWS', 'GCP', 'Linux'],
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    profileCompletion: 85,
    status: 'active',
  },
  {
    id: 'user_seeker_5',
    email: 'meera.iyer@example.com',
    role: USER_ROLES.JOB_SEEKER,
    name: 'Meera Iyer',
    headline: 'Data Scientist & Machine Learning Engineer',
    location: 'Hyderabad, Telangana',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'NLP', 'Scikit-learn', 'SQL', 'LLMs'],
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    profileCompletion: 90,
    status: 'active',
  },
];

export const INITIAL_COMPANIES = [
  {
    id: 'comp_1',
    name: 'TechCorp Innovations',
    tagline: 'Empowering enterprise transformation with next-gen AI cloud solutions',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
    industry: 'Software & Cloud Services',
    size: '500-1,000 employees',
    founded: 2017,
    website: 'https://techcorp-innovations.demo',
    location: 'Ahmedabad, Gujarat',
    rating: 4.8,
    reviewCount: 142,
    verified: true,
    description: 'TechCorp Innovations is an industry-leading software powerhouse engineering enterprise cloud platforms, generative AI tooling, and high-performance financial systems.',
    benefits: ['Comprehensive Health Insurance', 'Remote-First Flexibility', 'Annual Learning Allowance (₹1,00,000)', 'Stock Options (ESOPs)', 'Free Catered Meals & Gym Membership'],
  },
  {
    id: 'comp_2',
    name: 'Google India',
    tagline: 'Organizing the world’s information and making it universally accessible',
    logo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
    industry: 'Internet & Technology',
    size: '10,000+ employees',
    founded: 1998,
    website: 'https://careers.google.com',
    location: 'Bangalore, Karnataka',
    rating: 4.9,
    reviewCount: 1890,
    verified: true,
    description: 'Google’s innovative search, Android, Cloud, and AI technologies touch billions of lives every single day across the globe.',
    benefits: ['World-class Campus & Micro-kitchens', 'Generous 401k & PF Matching', 'Wellness Stipend', 'Global Mobility Programs'],
  },
  {
    id: 'comp_3',
    name: 'Microsoft India',
    tagline: 'Empowering every person and every organization on the planet to achieve more',
    logo: 'https://images.unsplash.com/photo-1633409381659-4554366a7b7a?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1200&auto=format&fit=crop&q=80',
    industry: 'Software & Cloud Computing',
    size: '10,000+ employees',
    founded: 1975,
    website: 'https://careers.microsoft.com',
    location: 'Hyderabad, Telangana',
    rating: 4.7,
    reviewCount: 1540,
    verified: true,
    description: 'Microsoft enables digital transformation for the era of an intelligent cloud and an intelligent edge.',
    benefits: ['Hybrid Work Model', 'Parental Leave (20 weeks)', 'Product Discounts', 'Extensive Learning & Mentorship'],
  },
  {
    id: 'comp_4',
    name: 'Swiggy',
    tagline: 'Delivering happiness and groceries in minutes across India',
    logo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&auto=format&fit=crop&q=80',
    industry: 'FoodTech & Quick Commerce',
    size: '5,000-10,000 employees',
    founded: 2014,
    website: 'https://swiggy.com',
    location: 'Bangalore, Karnataka',
    rating: 4.4,
    reviewCount: 820,
    verified: true,
    description: 'Swiggy is India’s leading on-demand convenience platform operating across 500+ cities.',
    benefits: ['Swiggy Dineout Credits', 'Medical Shield for Family', 'Flexible PTO', 'Annual Hackathons'],
  },
  {
    id: 'comp_5',
    name: 'Zomato & Blinkit',
    tagline: 'Better food for more people, delivered at lightning speed',
    logo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80',
    industry: 'E-commerce & FoodTech',
    size: '5,000-10,000 employees',
    founded: 2008,
    website: 'https://zomato.com',
    location: 'Delhi NCR, India',
    rating: 4.3,
    reviewCount: 710,
    verified: true,
    description: 'Zomato is a pioneering food ecosystem connecting customers, delivery partners, and restaurant owners.',
    benefits: ['No Formal Dress Code', 'Unlimited Time Off for Critical Care', 'Stock Grants', 'Pet-Friendly Office'],
  },
  {
    id: 'comp_6',
    name: 'CRED',
    tagline: 'Rewards for the creditworthy and financial high-flyers',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
    industry: 'Fintech & Lifestyle',
    size: '1,000-5,000 employees',
    founded: 2018,
    website: 'https://cred.club',
    location: 'Bangalore, Karnataka',
    rating: 4.6,
    reviewCount: 460,
    verified: true,
    description: 'CRED is a members-only club that rewards individuals for timely credit card payments and smart wealth growth.',
    benefits: ['Top-tier Compensation in India', 'High-end Apple Workstations', 'Personal Fitness Coach', 'Mental Health Support'],
  },
  {
    id: 'comp_7',
    name: 'Razorpay',
    tagline: 'The financial backbone and payment infrastructure of Indian commerce',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&auto=format&fit=crop&q=80',
    industry: 'Fintech & Neo-Banking',
    size: '1,000-5,000 employees',
    founded: 2014,
    website: 'https://razorpay.com',
    location: 'Bangalore, Karnataka',
    rating: 4.6,
    reviewCount: 650,
    verified: true,
    description: 'Razorpay powers payments for over 10 million Indian businesses, offering payment gateways, payroll, and banking API suites.',
    benefits: ['Health Insurance with Zero Waiting Period', 'Work from Anywhere Allowance', 'Annual ESOP Buyback Program'],
  },
  {
    id: 'comp_8',
    name: 'Tata Consultancy Services',
    tagline: 'Building on belief to engineer global business transformation',
    logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1200&auto=format&fit=crop&q=80',
    industry: 'IT Services & Consulting',
    size: '100,000+ employees',
    founded: 1968,
    website: 'https://tcs.com',
    location: 'Mumbai, Maharashtra',
    rating: 4.1,
    reviewCount: 3400,
    verified: true,
    description: 'TCS is a global IT services and consulting organization partnering with world business leaders.',
    benefits: ['Job Stability & Global Exposure', 'Tata Group Employee Discounts', 'Comprehensive Pension Plans'],
  },
  {
    id: 'comp_9',
    name: 'Zerodha',
    tagline: 'India’s largest discount broker pioneering free equity investments',
    logo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=1200&auto=format&fit=crop&q=80',
    industry: 'Fintech & Stock Broking',
    size: '1,000-5,000 employees',
    founded: 2010,
    website: 'https://zerodha.com',
    location: 'Bangalore, Karnataka',
    rating: 4.9,
    reviewCount: 520,
    verified: true,
    description: 'Zerodha disrupted Indian capital markets through zero brokerage trading and modern open-source web tech stack.',
    benefits: ['Zero Micromanagement', 'Generous Annual Profit Sharing', 'Flexible Remote Schedules', 'Tech First Freedom'],
  },
  {
    id: 'comp_10',
    name: 'Freshworks',
    tagline: 'Delivering delightful modern SaaS software for customer support and IT',
    logo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&auto=format&fit=crop&q=80',
    industry: 'Enterprise SaaS',
    size: '5,000-10,000 employees',
    founded: 2010,
    website: 'https://freshworks.com',
    location: 'Chennai, Tamil Nadu',
    rating: 4.5,
    reviewCount: 680,
    verified: true,
    description: 'Freshworks builds cloud SaaS software that helps businesses delight customers and employees.',
    benefits: ['NASDAQ Listed Equity (RSUs)', 'Global Relocation Support', 'Daycare Facility on Campus'],
  },
  {
    id: 'comp_11',
    name: 'Flipkart',
    tagline: 'Transforming e-commerce across India for millions of daily shoppers',
    logo: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?w=1200&auto=format&fit=crop&q=80',
    industry: 'E-commerce & Logistics',
    size: '10,000+ employees',
    founded: 2007,
    website: 'https://flipkart.com',
    location: 'Bangalore, Karnataka',
    rating: 4.4,
    reviewCount: 1420,
    verified: true,
    description: 'Flipkart is one of India’s premier digital commerce marketplaces owned by Walmart.',
    benefits: ['Paternity & Maternity Coverage', 'Discounts across Flipkart ecosystem', 'Wellness Reimbursements'],
  },
  {
    id: 'comp_12',
    name: 'Infosys Technologies',
    tagline: 'Navigating your next with AI-powered digital enterprise innovation',
    logo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=120&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&auto=format&fit=crop&q=80',
    industry: 'IT Services & Consulting',
    size: '100,000+ employees',
    founded: 1981,
    website: 'https://infosys.com',
    location: 'Pune, Maharashtra',
    rating: 4.0,
    reviewCount: 2900,
    verified: true,
    description: 'Infosys is a global leader in next-generation digital services, consulting, and cloud transformation.',
    benefits: ['Vast Training Academy (Mysore)', 'Health & Life Insurance', 'International Client Transfers'],
  },
];

export const INITIAL_JOBS = [
  {
    id: 'job_1',
    title: 'Senior Frontend Engineer (React & Next.js)',
    companyId: 'comp_1',
    companyName: 'TechCorp Innovations',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    location: 'Ahmedabad, Gujarat',
    workplaceType: 'hybrid',
    jobType: 'full-time',
    experienceLevel: 'senior',
    salaryMin: 1800000,
    salaryMax: 2800000,
    salaryCurrency: 'INR',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Redux', 'GraphQL'],
    description: 'We are seeking an exceptional Senior Frontend Engineer to architect and scale our core SaaS dashboard. You will lead UI engineering initiatives, implement real-time analytics visualizations, and mentor junior developers.',
    responsibilities: [
      'Architect resilient, fast client applications with React 18 and Next.js',
      'Optimize web performance and ensure seamless 60fps user experience',
      'Collaborate closely with product designers, product managers, and backend engineers',
      'Maintain strong unit and end-to-end test coverage with Vitest and Playwright',
    ],
    requirements: [
      '5+ years of production experience in modern React ecosystem',
      'Deep understanding of browser rendering, state management, and async patterns',
      'Strong eye for UI/UX micro-interactions and responsive design',
      'Bachelor’s or Master’s in Computer Science or equivalent practical experience',
    ],
    benefits: ['₹22L - ₹28L CTC + ESOPs', 'Flexible work from home 2 days/week', 'Comprehensive Family Health Insurance', 'Annual Tech Conference budget'],
    postedAt: '2026-10-02T10:00:00.000Z',
    expiresAt: '2026-11-15T23:59:59.000Z',
    status: 'active',
    applicantCount: 24,
    viewsCount: 312,
    featured: true,
  },
  {
    id: 'job_2',
    title: 'Full Stack Node.js & React Developer',
    companyId: 'comp_7',
    companyName: 'Razorpay',
    companyLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
    location: 'Bangalore, Karnataka',
    workplaceType: 'on-site',
    jobType: 'full-time',
    experienceLevel: 'mid',
    salaryMin: 2200000,
    salaryMax: 3200000,
    salaryCurrency: 'INR',
    skills: ['Node.js', 'React', 'TypeScript', 'PostgreSQL', 'Redis', 'Kafka', 'Docker'],
    description: 'Join the Razorpay core checkout engineering team. Build high-throughput financial transaction processing flows serving millions of users daily with 99.999% uptime.',
    responsibilities: [
      'Design fault-tolerant APIs and microservices in Node.js and Go',
      'Build seamless payment widgets with React and vanilla JS SDKs',
      'Ensure strict PCI-DSS security compliance across all endpoints',
    ],
    requirements: [
      '3-6 years of experience in full-stack web applications',
      'Proficiency with SQL optimization and distributed caching',
      'Strong knowledge of concurrency and idempotency in distributed payment systems',
    ],
    benefits: ['Competitive salary + RSUs', 'Daily catered gourmet lunches', 'Generous wellness & gym allowance'],
    postedAt: '2026-10-04T09:30:00.000Z',
    status: 'active',
    applicantCount: 42,
    viewsCount: 540,
    featured: true,
  },
  {
    id: 'job_3',
    title: 'Lead UI/UX Product Designer',
    companyId: 'comp_6',
    companyName: 'CRED',
    companyLogo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=120&auto=format&fit=crop&q=80',
    location: 'Bangalore, Karnataka',
    workplaceType: 'hybrid',
    jobType: 'full-time',
    experienceLevel: 'lead',
    salaryMin: 3000000,
    salaryMax: 4500000,
    salaryCurrency: 'INR',
    skills: ['Figma', 'UI/UX Design', 'Design Systems', 'Micro-interactions', 'Prototyping', 'User Research'],
    description: 'CRED is known for industry-defining aesthetic craft. We are looking for a visionary Lead Product Designer who obsessively polishes every pixel and motion curve to create unforgettable consumer experiences.',
    responsibilities: [
      'Own end-to-end design for new lifestyle and wealth product lines',
      'Craft tactile 3D/2D interactive components and fluid animations',
      'Run qualitative user research sessions and translate insights into prototypes',
    ],
    requirements: [
      '6+ years creating award-winning digital consumer experiences',
      'A stellar portfolio demonstrating high visual craft and motion design',
      'Deep mastery of Figma, Principle, or Protopie',
    ],
    benefits: ['Industry-leading compensation & equity', 'Custom Apple M3 Max setup', 'Unlimited book & learning budget'],
    postedAt: '2026-10-05T14:00:00.000Z',
    status: 'active',
    applicantCount: 18,
    viewsCount: 480,
    featured: true,
  },
  {
    id: 'job_4',
    title: 'Backend Go / Python Engineer',
    companyId: 'comp_9',
    companyName: 'Zerodha',
    companyLogo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=120&auto=format&fit=crop&q=80',
    location: 'Remote (India)',
    workplaceType: 'remote',
    jobType: 'full-time',
    experienceLevel: 'mid',
    salaryMin: 2000000,
    salaryMax: 3000000,
    salaryCurrency: 'INR',
    skills: ['Go', 'Python', 'PostgreSQL', 'Redis', 'WebSockets', 'Linux'],
    description: 'Work directly on Kite, India’s largest stock trading platform. We write minimalist, fast software that processes over 15 million orders every trading day.',
    responsibilities: [
      'Develop real-time market data streaming feeds via WebSockets',
      'Scale order validation and execution engines with low latency Go code',
      'Contribute to internal open source tooling and libraries',
    ],
    requirements: [
      'Strong fundamentals in operating systems, networking, and data structures',
      'Experience building low-latency distributed systems in Go or Python',
      'Love for simple code and zero bloated frameworks',
    ],
    benefits: ['100% remote anywhere in India', 'Generous year-end profit sharing bonuses', 'No micromanagement culture'],
    postedAt: '2026-10-01T11:00:00.000Z',
    status: 'active',
    applicantCount: 65,
    viewsCount: 920,
    featured: true,
  },
  {
    id: 'job_5',
    title: 'DevOps & Site Reliability Engineer',
    companyId: 'comp_4',
    companyName: 'Swiggy',
    companyLogo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=120&auto=format&fit=crop&q=80',
    location: 'Bangalore, Karnataka',
    workplaceType: 'hybrid',
    jobType: 'full-time',
    experienceLevel: 'senior',
    salaryMin: 2500000,
    salaryMax: 3800000,
    salaryCurrency: 'INR',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'Docker', 'Prometheus', 'CI/CD', 'Golang'],
    description: 'Manage massive cloud scale handling peak dinner-time rushes with millions of concurrent orders. Keep Swiggy’s delivery ecosystem lightning fast and resilient.',
    responsibilities: [
      'Scale multi-region Kubernetes clusters on AWS',
      'Automate infrastructure provisioning using Terraform & GitOps',
      'Improve observability with Grafana, Prometheus, and OpenTelemetry',
    ],
    requirements: [
      '5+ years in SRE/DevOps roles for high-traffic consumer tech platforms',
      'Deep hands-on experience with container orchestration and chaos engineering',
    ],
    benefits: ['Comprehensive health coverage', 'Food vouchers & discounts', 'Relocation assistance to Bangalore'],
    postedAt: '2026-09-28T08:00:00.000Z',
    status: 'active',
    applicantCount: 31,
    viewsCount: 410,
    featured: false,
  },
  {
    id: 'job_6',
    title: 'AI / Machine Learning Engineer (LLMs & RAG)',
    companyId: 'comp_1',
    companyName: 'TechCorp Innovations',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    location: 'Ahmedabad, Gujarat',
    workplaceType: 'hybrid',
    jobType: 'full-time',
    experienceLevel: 'mid',
    salaryMin: 2000000,
    salaryMax: 3200000,
    salaryCurrency: 'INR',
    skills: ['Python', 'PyTorch', 'LangChain', 'LlamaIndex', 'Vector DBs', 'OpenAI API', 'FastAPI'],
    description: 'Build enterprise-grade AI agents, semantic retrieval pipelines, and custom fine-tuned LLMs for document intelligence and enterprise automation.',
    responsibilities: [
      'Build and optimize retrieval augmented generation (RAG) pipelines',
      'Evaluate model hallucinations, latency, and cost tradeoffs',
      'Deploy production inference APIs using FastAPI and Triton Server',
    ],
    requirements: [
      '3+ years in Applied ML / NLP with proven generative AI experience',
      'Familiarity with Milvus, Pinecone, or Qdrant vector databases',
    ],
    benefits: ['Top-end Nvidia GPU workstation', 'Flexible hours', 'ESOP grants'],
    postedAt: '2026-10-03T16:20:00.000Z',
    status: 'active',
    applicantCount: 19,
    viewsCount: 380,
    featured: true,
  },
  {
    id: 'job_7',
    title: 'Junior React Frontend Developer',
    companyId: 'comp_10',
    companyName: 'Freshworks',
    companyLogo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=120&auto=format&fit=crop&q=80',
    location: 'Chennai, Tamil Nadu',
    workplaceType: 'on-site',
    jobType: 'full-time',
    experienceLevel: 'junior',
    salaryMin: 700000,
    salaryMax: 1200000,
    salaryCurrency: 'INR',
    skills: ['React', 'JavaScript', 'HTML5', 'CSS3', 'Git', 'REST APIs'],
    description: 'Kickstart your career with Freshworks. Work with a vibrant engineering team crafting intuitive widgets and components for our global customer support suite.',
    responsibilities: [
      'Build reusable UI components following design system guidelines',
      'Fix frontend bugs and assist with unit test cases',
    ],
    requirements: [
      '1-2 years of experience or strong portfolio projects with React',
      'Good understanding of HTML5, CSS Flexbox/Grid, and modern JavaScript (ES6+)',
    ],
    benefits: ['Structured mentorship program', 'Campus meals & sports facilities', 'Health insurance'],
    postedAt: '2026-10-06T12:00:00.000Z',
    status: 'active',
    applicantCount: 78,
    viewsCount: 650,
    featured: false,
  },
  {
    id: 'job_8',
    title: 'Product Manager - Growth & Retention',
    companyId: 'comp_5',
    companyName: 'Zomato & Blinkit',
    companyLogo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=120&auto=format&fit=crop&q=80',
    location: 'Delhi NCR, India',
    workplaceType: 'on-site',
    jobType: 'full-time',
    experienceLevel: 'senior',
    salaryMin: 2800000,
    salaryMax: 4200000,
    salaryCurrency: 'INR',
    skills: ['Product Strategy', 'A/B Testing', 'SQL', 'Data Analytics', 'User Experience'],
    description: 'Lead high-impact growth loops, cart conversion optimizations, and loyalty program initiatives across Zomato Gold.',
    responsibilities: [
      'Define OKRs and feature roadmaps for customer activation and retention',
      'Run rigorous experimentation and data deep-dives with analytics teams',
    ],
    requirements: [
      '4+ years product management experience in high-growth B2C internet apps',
      'Strong quantitative and analytical mindset with SQL fluency',
    ],
    benefits: ['Executive compensation package', 'Zomato Gold VIP membership for family', 'Annual offsites'],
    postedAt: '2026-09-30T10:00:00.000Z',
    status: 'active',
    applicantCount: 35,
    viewsCount: 520,
    featured: false,
  },
  {
    id: 'job_9',
    title: 'React Native Mobile Developer (iOS & Android)',
    companyId: 'comp_11',
    companyName: 'Flipkart',
    companyLogo: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=120&auto=format&fit=crop&q=80',
    location: 'Bangalore, Karnataka',
    workplaceType: 'hybrid',
    jobType: 'full-time',
    experienceLevel: 'mid',
    salaryMin: 1800000,
    salaryMax: 2600000,
    salaryCurrency: 'INR',
    skills: ['React Native', 'JavaScript', 'TypeScript', 'Redux', 'Mobile Performance', 'Native Modules'],
    description: 'Work on one of India’s most installed mobile applications. Ensure rapid app boot time, smooth 60fps catalog browsing, and seamless offline caching.',
    responsibilities: [
      'Build feature modules in React Native with custom Swift/Kotlin bridging',
      'Profile memory, battery usage, and network consumption',
    ],
    requirements: [
      '3+ years shipping production React Native apps on App Store and Play Store',
      'Understanding of native iOS / Android build lifecycles',
    ],
    benefits: ['Relocation bonus', 'Wellness allowance', 'Annual performance incentives'],
    postedAt: '2026-10-02T13:45:00.000Z',
    status: 'active',
    applicantCount: 29,
    viewsCount: 390,
    featured: false,
  },
  {
    id: 'job_10',
    title: 'Cybersecurity Analyst & SOC Specialist',
    companyId: 'comp_8',
    companyName: 'Tata Consultancy Services',
    companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    location: 'Mumbai, Maharashtra',
    workplaceType: 'on-site',
    jobType: 'full-time',
    experienceLevel: 'mid',
    salaryMin: 1200000,
    salaryMax: 1800000,
    salaryCurrency: 'INR',
    skills: ['Cybersecurity', 'SIEM', 'Threat Hunting', 'Network Security', 'Firewalls', 'Incident Response'],
    description: 'Monitor global client security perimeters, investigate intrusion alerts, and implement defensive countermeasures.',
    responsibilities: [
      'Analyze logs in SIEM platforms (Splunk, Sentinel) to detect unauthorized activities',
      'Participate in red/blue team simulations and vulnerability assessments',
    ],
    requirements: [
      '3+ years in security operations center (SOC) environments',
      'Certifications like CEH, CompTIA Security+, or CISSP are preferred',
    ],
    benefits: ['Tata Group benefits', 'Shift allowances', 'Continuous cybersecurity certification sponsorships'],
    postedAt: '2026-09-25T15:00:00.000Z',
    status: 'active',
    applicantCount: 45,
    viewsCount: 470,
    featured: false,
  },
  {
    id: 'job_11',
    title: 'Cloud Infrastructure Architect',
    companyId: 'comp_3',
    companyName: 'Microsoft India',
    companyLogo: 'https://images.unsplash.com/photo-1633409381659-4554366a7b7a?w=120&auto=format&fit=crop&q=80',
    location: 'Hyderabad, Telangana',
    workplaceType: 'hybrid',
    jobType: 'full-time',
    experienceLevel: 'lead',
    salaryMin: 4000000,
    salaryMax: 6000000,
    salaryCurrency: 'INR',
    skills: ['Azure', 'Cloud Architecture', 'Kubernetes', 'Security', 'Enterprise Scalability'],
    description: 'Partner with Fortune 500 enterprises to design and execute cloud transformation strategies leveraging Microsoft Azure.',
    responsibilities: [
      'Design mission-critical multi-region architectures with high availability',
      'Provide technical guidance to C-level stakeholders',
    ],
    requirements: [
      '8+ years in cloud computing architecture',
      'Deep mastery of Microsoft Azure or AWS enterprise solutions',
    ],
    benefits: ['RSUs + Microsoft Employee Stock Purchase Program', 'Comprehensive Healthcare', 'Flexible work'],
    postedAt: '2026-10-04T17:00:00.000Z',
    status: 'active',
    applicantCount: 15,
    viewsCount: 310,
    featured: true,
  },
  {
    id: 'job_12',
    title: 'Senior Quality Assurance Automation Engineer',
    companyId: 'comp_12',
    companyName: 'Infosys Technologies',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=120&auto=format&fit=crop&q=80',
    location: 'Pune, Maharashtra',
    workplaceType: 'hybrid',
    jobType: 'full-time',
    experienceLevel: 'senior',
    salaryMin: 1400000,
    salaryMax: 2000000,
    salaryCurrency: 'INR',
    skills: ['Playwright', 'Selenium', 'Cypress', 'Java', 'Python', 'API Testing', 'Jenkins'],
    description: 'Build enterprise test automation suites, performance load testing frameworks, and continuous integration pipelines.',
    responsibilities: [
      'Write scalable automated test scripts in TypeScript / Java',
      'Execute load and stress testing using JMeter and k6',
    ],
    requirements: [
      '5+ years in QA automation testing for web and mobile platforms',
    ],
    benefits: ['Infosys campus amenities', 'Group medical cover', 'Annual bonus'],
    postedAt: '2026-09-29T10:00:00.000Z',
    status: 'active',
    applicantCount: 52,
    viewsCount: 420,
    featured: false,
  },
  {
    id: 'job_13',
    title: 'Frontend Intern (React & Tailwind)',
    companyId: 'comp_1',
    companyName: 'TechCorp Innovations',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    location: 'Ahmedabad, Gujarat',
    workplaceType: 'hybrid',
    jobType: 'internship',
    experienceLevel: 'fresher',
    salaryMin: 25000,
    salaryMax: 40000,
    salaryCurrency: 'INR',
    skills: ['React', 'JavaScript', 'HTML5', 'Tailwind CSS', 'Git'],
    description: '6-month paid internship with pre-placement full-time offer opportunity. Learn modern React, Vite, and component design patterns while collaborating with senior engineers.',
    responsibilities: [
      'Build landing pages, marketing widgets, and internal utility tools',
      'Write clean, accessible, and responsive components',
    ],
    requirements: [
      'Recent graduate or final year student in Computer Science / IT',
      'Strong passion for frontend technologies and hands-on personal projects',
    ],
    benefits: ['₹35,000/month stipend', 'Opportunity for full-time conversion', 'Certificate of Completion & Letter of Recommendation'],
    postedAt: '2026-10-06T15:00:00.000Z',
    status: 'active',
    applicantCount: 110,
    viewsCount: 880,
    featured: true,
  },
  {
    id: 'job_14',
    title: 'Freelance Technical Content Writer (DevRel)',
    companyId: 'comp_9',
    companyName: 'Zerodha',
    companyLogo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=120&auto=format&fit=crop&q=80',
    location: 'Remote (Worldwide)',
    workplaceType: 'remote',
    jobType: 'freelance',
    experienceLevel: 'mid',
    salaryMin: 50000,
    salaryMax: 100000,
    salaryCurrency: 'INR',
    skills: ['Technical Writing', 'Developer Documentation', 'Python', 'Trading APIs', 'Markdown'],
    description: 'Write developer guides, API tutorials, and architectural breakdown blogs for the developer community building on Kite APIs.',
    responsibilities: [
      'Produce 3-4 in-depth technical blogs and code sample repos per month',
      'Review developer documentation for clarity and code accuracy',
    ],
    requirements: [
      'Strong technical background with ability to write clean Python scripts',
      'Excellent writing samples and public blog posts',
    ],
    benefits: ['Flexible per-article compensation', 'Complete remote freedom'],
    postedAt: '2026-10-05T09:00:00.000Z',
    status: 'active',
    applicantCount: 22,
    viewsCount: 290,
    featured: false,
  },
  {
    id: 'job_15',
    title: 'Senior Data Engineer (Snowflake & Spark)',
    companyId: 'comp_4',
    companyName: 'Swiggy',
    companyLogo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=120&auto=format&fit=crop&q=80',
    location: 'Bangalore, Karnataka',
    workplaceType: 'hybrid',
    jobType: 'full-time',
    experienceLevel: 'senior',
    salaryMin: 2400000,
    salaryMax: 3600000,
    salaryCurrency: 'INR',
    skills: ['Apache Spark', 'Snowflake', 'Python', 'SQL', 'Airflow', 'Kafka', 'dbt'],
    description: 'Design and manage large-scale data lakehouses processing billions of real-time events for delivery logistics optimization.',
    responsibilities: [
      'Build robust batch and streaming ETL data pipelines',
      'Optimize data warehouse schemas and query performance',
    ],
    requirements: [
      '4-7 years of experience in data engineering with PySpark and Snowflake',
    ],
    benefits: ['Generous compensation', 'Swiggy food credits', 'Health coverage'],
    postedAt: '2026-10-01T14:30:00.000Z',
    status: 'active',
    applicantCount: 28,
    viewsCount: 340,
    featured: false,
  },
];

// Generate remaining mock jobs (up to 42 jobs) programmatically to reach 40+ jobs requirement
const jobTitlesAndSkills = [
  { title: 'Frontend Developer (Vue & Nuxt)', skills: ['Vue.js', 'Nuxt', 'JavaScript', 'Tailwind CSS'], type: 'full-time', exp: 'mid', min: 1200000, max: 1800000, loc: 'Pune, Maharashtra', comp: 'comp_10' },
  { title: 'Software Engineer - Cloud Platform', skills: ['Golang', 'Kubernetes', 'Docker', 'GCP'], type: 'full-time', exp: 'senior', min: 2500000, max: 3500000, loc: 'Bangalore, Karnataka', comp: 'comp_2' },
  { title: 'Database Administrator (PostgreSQL & MongoDB)', skills: ['PostgreSQL', 'MongoDB', 'Database Tuning', 'Linux'], type: 'full-time', exp: 'senior', min: 1600000, max: 2400000, loc: 'Mumbai, Maharashtra', comp: 'comp_8' },
  { title: 'iOS App Developer (Swift & SwiftUI)', skills: ['Swift', 'SwiftUI', 'iOS', 'CoreData', 'Combine'], type: 'full-time', exp: 'mid', min: 1800000, max: 2700000, loc: 'Bangalore, Karnataka', comp: 'comp_6' },
  { title: 'Android Developer (Kotlin & Jetpack Compose)', skills: ['Kotlin', 'Jetpack Compose', 'Android', 'Coroutines'], type: 'full-time', exp: 'mid', min: 1700000, max: 2600000, loc: 'Delhi NCR, India', comp: 'comp_5' },
  { title: 'Security Engineer - Application Security', skills: ['AppSec', 'Penetration Testing', 'OWASP', 'Python'], type: 'full-time', exp: 'senior', min: 2200000, max: 3400000, loc: 'Bangalore, Karnataka', comp: 'comp_7' },
  { title: 'Growth Marketing Manager', skills: ['Performance Marketing', 'SEO', 'Google Ads', 'Analytics'], type: 'full-time', exp: 'mid', min: 1400000, max: 2200000, loc: 'Ahmedabad, Gujarat', comp: 'comp_1' },
  { title: 'Human Resources Talent Partner', skills: ['Recruiting', 'HR Management', 'Talent Sourcing', 'Communication'], type: 'full-time', exp: 'junior', min: 600000, max: 900000, loc: 'Mumbai, Maharashtra', comp: 'comp_12' },
  { title: 'Data Analyst - Business Intelligence', skills: ['SQL', 'Tableau', 'Power BI', 'Python', 'Excel'], type: 'full-time', exp: 'junior', min: 700000, max: 1100000, loc: 'Ahmedabad, Gujarat', comp: 'comp_1' },
  { title: 'Senior Java Backend Architect', skills: ['Java', 'Spring Boot', 'Microservices', 'Kafka', 'AWS'], type: 'full-time', exp: 'lead', min: 3200000, max: 4800000, loc: 'Pune, Maharashtra', comp: 'comp_12' },
  { title: 'Contract Solutions Architect', skills: ['AWS', 'Microservices', 'System Design', 'Docker'], type: 'contract', exp: 'senior', min: 2000000, max: 3000000, loc: 'Remote (India)', comp: 'comp_3' },
  { title: 'Part-Time UX Copywriter', skills: ['Copywriting', 'UX Writing', 'Content Strategy'], type: 'part-time', exp: 'mid', min: 400000, max: 800000, loc: 'Remote (Worldwide)', comp: 'comp_6' },
  { title: 'Full Stack Web Developer (MERN)', skills: ['MongoDB', 'Express', 'React', 'Node.js', 'Tailwind CSS'], type: 'full-time', exp: 'junior', min: 600000, max: 1000000, loc: 'Ahmedabad, Gujarat', comp: 'comp_1' },
  { title: 'Staff Systems Engineer', skills: ['Rust', 'C++', 'Distributed Systems', 'Linux Kernel'], type: 'full-time', exp: 'lead', min: 4500000, max: 6500000, loc: 'Bangalore, Karnataka', comp: 'comp_2' },
  { title: 'Associate Product Operations Specialist', skills: ['Operations', 'Jira', 'Agile', 'Customer Feedback'], type: 'full-time', exp: 'fresher', min: 500000, max: 750000, loc: 'Bangalore, Karnataka', comp: 'comp_4' },
  { title: 'Ruby on Rails Developer', skills: ['Ruby', 'Rails', 'PostgreSQL', 'Redis', 'RSpec'], type: 'full-time', exp: 'mid', min: 1400000, max: 2100000, loc: 'Remote (India)', comp: 'comp_10' },
  { title: 'NLP Researcher & Scientist', skills: ['NLP', 'Transformers', 'HuggingFace', 'Python', 'PyTorch'], type: 'full-time', exp: 'senior', min: 2800000, max: 4200000, loc: 'Bangalore, Karnataka', comp: 'comp_2' },
  { title: 'Graphic & Brand Visual Designer', skills: ['Illustrator', 'Photoshop', 'Branding', 'Figma'], type: 'full-time', exp: 'junior', min: 600000, max: 950000, loc: 'Delhi NCR, India', comp: 'comp_5' },
  { title: 'Customer Success Manager (B2B SaaS)', skills: ['SaaS', 'Account Management', 'CRM', 'Client Relations'], type: 'full-time', exp: 'mid', min: 1100000, max: 1600000, loc: 'Chennai, Tamil Nadu', comp: 'comp_10' },
  { title: 'Site Reliability Engineer - Cloud Security', skills: ['AWS', 'Terraform', 'Kubernetes', 'Python', 'Security'], type: 'full-time', exp: 'senior', min: 2600000, max: 3800000, loc: 'Bangalore, Karnataka', comp: 'comp_7' },
  { title: 'Blockchain & Web3 Smart Contract Engineer', skills: ['Solidity', 'Ethereum', 'Rust', 'Web3.js', 'EVM'], type: 'full-time', exp: 'senior', min: 2800000, max: 4500000, loc: 'Remote (Worldwide)', comp: 'comp_6' },
  { title: 'Lead Automation QA (Python & Pytest)', skills: ['Python', 'Pytest', 'Selenium', 'CI/CD', 'Docker'], type: 'full-time', exp: 'lead', min: 2400000, max: 3400000, loc: 'Ahmedabad, Gujarat', comp: 'comp_1' },
  { title: 'Junior Data Scientist', skills: ['Python', 'Pandas', 'Scikit-learn', 'SQL', 'Matplotlib'], type: 'full-time', exp: 'fresher', min: 650000, max: 950000, loc: 'Bangalore, Karnataka', comp: 'comp_4' },
  { title: 'Scrum Master & Agile Coach', skills: ['Scrum', 'Agile', 'Jira', 'Kanban', 'Sprint Planning'], type: 'full-time', exp: 'senior', min: 1800000, max: 2600000, loc: 'Mumbai, Maharashtra', comp: 'comp_8' },
  { title: 'Technical Support Engineer (L2/L3)', skills: ['Linux', 'Networking', 'SQL', 'Troubleshooting', 'REST APIs'], type: 'full-time', exp: 'junior', min: 550000, max: 800000, loc: 'Pune, Maharashtra', comp: 'comp_12' },
  { title: 'Principal Solution Architect - Enterprise AI', skills: ['Generative AI', 'Solution Architecture', 'Azure', 'Enterprise Integration'], type: 'full-time', exp: 'lead', min: 5000000, max: 7500000, loc: 'Hyderabad, Telangana', comp: 'comp_3' },
  { title: 'Mobile React Native Intern', skills: ['React Native', 'JavaScript', 'CSS', 'Git'], type: 'internship', exp: 'fresher', min: 20000, max: 35000, loc: 'Bangalore, Karnataka', comp: 'comp_11' },
];

jobTitlesAndSkills.forEach((item, index) => {
  const comp = INITIAL_COMPANIES.find((c) => c.id === item.comp) || INITIAL_COMPANIES[0];
  INITIAL_JOBS.push({
    id: `job_${index + 16}`,
    title: item.title,
    companyId: comp.id,
    companyName: comp.name,
    companyLogo: comp.logo,
    location: item.loc,
    workplaceType: item.loc.toLowerCase().includes('remote') ? 'remote' : index % 2 === 0 ? 'hybrid' : 'on-site',
    jobType: item.type,
    experienceLevel: item.exp,
    salaryMin: item.min,
    salaryMax: item.max,
    salaryCurrency: 'INR',
    skills: item.skills,
    description: `We are looking for a talented ${item.title} to join our high-performing team at ${comp.name}. You will collaborate with cross-functional experts to ship scalable products and deliver immense customer value.`,
    responsibilities: [
      `Design, implement, and maintain mission-critical modules with ${item.skills[0]} and ${item.skills[1]}`,
      'Collaborate with agile development teams, participating in daily standups and code reviews',
      'Optimize code quality, scalability, and execution performance',
    ],
    requirements: [
      `Hands-on experience working with ${item.skills.slice(0, 3).join(', ')}`,
      'Solid problem solving skills and commitment to engineering excellence',
    ],
    benefits: ['Competitive compensation package', 'Health insurance & wellness benefits', 'Generous paid time off'],
    postedAt: new Date(Date.now() - (index + 2) * 86400000).toISOString(),
    status: 'active',
    applicantCount: Math.floor(Math.random() * 40) + 5,
    viewsCount: Math.floor(Math.random() * 500) + 120,
    featured: index % 5 === 0,
  });
});

export const INITIAL_APPLICATIONS = [
  {
    id: 'app_1',
    jobId: 'job_1',
    jobTitle: 'Senior Frontend Engineer (React & Next.js)',
    companyId: 'comp_1',
    companyName: 'TechCorp Innovations',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    location: 'Ahmedabad, Gujarat',
    seekerId: 'user_seeker_1',
    seekerName: 'Aarav Sharma',
    seekerEmail: 'seeker@jobconnect.demo',
    seekerHeadline: 'Senior Full Stack React & Node Developer',
    seekerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    resumeUrl: 'Aarav_Sharma_FullStack_Resume.pdf',
    coverLetter: 'Dear Hiring Team at TechCorp, I have spent the last 5+ years building performant React applications with Next.js and Redux. I would love to contribute to your core SaaS platforms.',
    status: APPLICATION_STATUS.INTERVIEW,
    appliedAt: '2026-10-03T11:20:00.000Z',
    timeline: [
      { status: APPLICATION_STATUS.APPLIED, date: '2026-10-03T11:20:00.000Z', note: 'Application submitted successfully' },
      { status: APPLICATION_STATUS.UNDER_REVIEW, date: '2026-10-04T09:15:00.000Z', note: 'Resume reviewed by Priya Patel (Recruiter)' },
      { status: APPLICATION_STATUS.SHORTLISTED, date: '2026-10-05T14:30:00.000Z', note: 'Candidate profile shortlisted for technical rounds' },
      { status: APPLICATION_STATUS.INTERVIEW, date: '2026-10-06T10:00:00.000Z', note: 'Technical Round 1 scheduled for tomorrow' },
    ],
  },
  {
    id: 'app_2',
    jobId: 'job_4',
    jobTitle: 'Backend Go / Python Engineer',
    companyId: 'comp_9',
    companyName: 'Zerodha',
    companyLogo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=120&auto=format&fit=crop&q=80',
    location: 'Remote (India)',
    seekerId: 'user_seeker_1',
    seekerName: 'Aarav Sharma',
    seekerEmail: 'seeker@jobconnect.demo',
    resumeUrl: 'Aarav_Sharma_FullStack_Resume.pdf',
    coverLetter: 'Excited about Zerodha’s tech ethos and low-overhead software engineering philosophy.',
    status: APPLICATION_STATUS.UNDER_REVIEW,
    appliedAt: '2026-10-04T15:40:00.000Z',
    timeline: [
      { status: APPLICATION_STATUS.APPLIED, date: '2026-10-04T15:40:00.000Z', note: 'Application submitted' },
      { status: APPLICATION_STATUS.UNDER_REVIEW, date: '2026-10-05T16:00:00.000Z', note: 'Under preliminary screening' },
    ],
  },
  {
    id: 'app_3',
    jobId: 'job_2',
    jobTitle: 'Full Stack Node.js & React Developer',
    companyId: 'comp_7',
    companyName: 'Razorpay',
    companyLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop&q=80',
    location: 'Bangalore, Karnataka',
    seekerId: 'user_seeker_1',
    seekerName: 'Aarav Sharma',
    seekerEmail: 'seeker@jobconnect.demo',
    resumeUrl: 'Aarav_Sharma_FullStack_Resume.pdf',
    coverLetter: 'I have hands-on experience building high-throughput REST APIs and checkout forms.',
    status: APPLICATION_STATUS.APPLIED,
    appliedAt: '2026-10-06T18:00:00.000Z',
    timeline: [
      { status: APPLICATION_STATUS.APPLIED, date: '2026-10-06T18:00:00.000Z', note: 'Application submitted' },
    ],
  },
];

export const INITIAL_REVIEWS = [
  {
    id: 'rev_1',
    companyId: 'comp_1',
    authorName: 'Senior Frontend Dev',
    rating: 5,
    title: 'Fantastic engineering culture and work-life balance',
    pros: 'High trust environment, great leadership, top-of-the-line MacBook Pros, supportive team.',
    cons: 'Fast-paced sprints can sometimes feel intense before major product launches.',
    role: 'Current Employee',
    createdAt: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'rev_2',
    companyId: 'comp_1',
    authorName: 'Product Designer',
    rating: 4.6,
    title: 'Collaborative team with high aesthetic standards',
    pros: 'Design is treated as a first-class citizen. Great ESOP upside.',
    cons: 'Need more cross-functional documentation as team scales.',
    role: 'Current Employee',
    createdAt: '2026-09-12T14:30:00.000Z',
  },
];

export const INITIAL_CHATS = [
  {
    id: 'chat_1',
    participants: ['user_seeker_1', 'user_employer_1'],
    seekerId: 'user_seeker_1',
    employerId: 'user_employer_1',
    jobId: 'job_1',
    jobTitle: 'Senior Frontend Engineer (React & Next.js)',
    lastMessage: 'Looking forward to our technical discussion tomorrow at 3:00 PM!',
    lastMessageAt: '2026-10-06T11:45:00.000Z',
    unreadCountSeeker: 0,
    unreadCountEmployer: 0,
    messages: [
      {
        id: 'msg_1',
        senderId: 'user_employer_1',
        text: 'Hi Aarav! We reviewed your profile and resume for the Senior Frontend Engineer role. Your background in React and micro-frontends looks fantastic.',
        timestamp: '2026-10-05T14:35:00.000Z',
      },
      {
        id: 'msg_2',
        senderId: 'user_seeker_1',
        text: 'Thank you Priya! I’m very excited about TechCorp’s recent AI products and would love to discuss how I can contribute.',
        timestamp: '2026-10-05T15:00:00.000Z',
      },
      {
        id: 'msg_3',
        senderId: 'user_employer_1',
        text: 'Wonderful. We have scheduled an interactive technical interview. Looking forward to our discussion tomorrow at 3:00 PM!',
        timestamp: '2026-10-06T11:45:00.000Z',
      },
    ],
  },
];

export const INITIAL_INTERVIEWS = [
  {
    id: 'int_1',
    jobId: 'job_1',
    jobTitle: 'Senior Frontend Engineer (React & Next.js)',
    companyName: 'TechCorp Innovations',
    seekerId: 'user_seeker_1',
    seekerName: 'Aarav Sharma',
    employerId: 'user_employer_1',
    employerName: 'Priya Patel',
    title: 'Round 1: System Design & React Architecture',
    date: '2026-10-08',
    startTime: '15:00',
    endTime: '16:00',
    status: 'confirmed', // 'proposed', 'confirmed', 'rescheduled', 'declined', 'completed'
    meetingLink: 'https://meet.jobconnect.demo/techcorp-aarav-frontend',
    notes: 'Please be prepared to walk through React state architecture, custom hooks, and web performance optimization techniques.',
    createdAt: '2026-10-06T10:00:00.000Z',
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif_1',
    userId: 'user_seeker_1',
    title: 'Interview Scheduled! 🎯',
    message: 'TechCorp Innovations scheduled "Round 1: System Design" for Oct 8 at 3:00 PM IST.',
    type: 'interview',
    read: false,
    link: '/seeker/interviews',
    createdAt: '2026-10-06T10:00:00.000Z',
  },
  {
    id: 'notif_2',
    userId: 'user_seeker_1',
    title: 'Application Shortlisted 🚀',
    message: 'Your application for Senior Frontend Engineer at TechCorp has been shortlisted!',
    type: 'application',
    read: true,
    link: '/seeker/applications',
    createdAt: '2026-10-05T14:30:00.000Z',
  },
  {
    id: 'notif_3',
    userId: 'user_seeker_1',
    title: 'New Recommended Job ✨',
    message: 'Razorpay posted "Full Stack Node.js & React Developer" matching 94% of your skills.',
    type: 'job_alert',
    read: true,
    link: '/jobs/job_2',
    createdAt: '2026-10-04T09:30:00.000Z',
  },
];
